# Site settings
title: Pointing to the Moon
description: Blog of William Zheng
baseurl: "" 
url: "https://zhengfangxing.github.io" 

# GitHub User settings
username: Boyisxuxu
github_username: zhengfangxing
user_description: A java developer with a broad interest
user_title: sexy programmers code online
email: boyisxuxu@gmail.com

# Blog Author settings
author:
  name:           William Zheng
  picture:        
  email:          boyisxuxu@gmail.com
  description:    I'm a java developer with a broad interest
  twitter:
  facebook:
  github:         https://github.com/zhengfangxing
  linkedin:


# markdown
markdown: kramdown
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  

permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true


exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"